# server04 网络配置 - DHCP服务器
network:
  version: 2
  ethernets:
    eth1:
      dhcp4: false
      dhcp6: false
    eth2:
      dhcp4: false
      dhcp6: false
  bonds:
    uplink:
      interfaces:
        - eth1
        - eth2
      parameters:
        mode: 802.3ad
        mii-monitor-interval: 100
        lacp-rate: fast
        transmit-hash-policy: layer3+4
      dhcp4: false
      dhcp6: false
      addresses: 
        - 172.30.1.100/16  # VLAN 1直接在bond上
  vlans:
    uplink.10:
      id: 10
      link: uplink
      addresses: 
        - 10.1.10.104/24
      routes:
        - to: 10.1.10.0/24
          via: 10.1.10.1
        - to: 10.1.20.0/24
          via: 10.1.10.1
